services:
  frontend:
    container_name: buna-sinni
    build:
      context: frontend/.
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    volumes:
      - .:/app:cached
      - /app/node_modules
      
    stdin_open: true
    tty: true
    networks:
      - buna-network
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}

networks:
  buna-network:
    driver: bridge

